version: "3.3"

services:  


  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb    
    volumes:
      - /opt/mongobing/data:/data/db
      - /opt/mongobing/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=Abcdf
      - MONGO_INITDB_ROOT_USERNAME=BingoBongo
    command: mongod
    networks:
      sky:
        aliases:
          - mongodb

  sky:
    image: sky   
    build: ./sky
    container_name: sky
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:      
      - mongodb     
    depends_on:     
      - mongodb        
    ports:
      - '2025:2025'
    volumes:
      - /opt/sky/logs/:/opt/sky/logs
    networks:
      - sky  


networks:
  sky:
    driver: bridge
