management:
  security:  
    enabled: false   
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: 'true'
      enabled-by-default: 'false'


server:
  port: 2025
  connection-timeout: 90000


spring:    
  application:
    name: sky
    
  data:
    mongodb:           
      uri: mongodb://BingoBongo:Abcdf@mongodb:27017/skyDB?ssl=false&connectTimeoutMS=300000&minPoolSize=0&maxPoolSize=100&maxIdleTimeMS=900000&readPreference=primaryPreferred&authSource=admin    


      
logging:
    level:
        ROOT: #logback.loglevel#
        com.optym: #logback.loglevel#
